#!/bin/bash
####################################################################################
###
### miniZ
### os.dog integration: @osdog
###
####################################################################################
. /dog/colors
cd `dirname $0`

CFG_FILENAME="miner.cfg"
. $CFG_FILENAME

LOG="/dog/log/miniz.log"

# Build command
batch="./miniZ"
[[ ! -z $ALGO ]]&& batch+=" --par=$ALGO"
[[ ! -z $PASS ]]&& batch+=" -p $PASS"
[[ ! -z $POOL && ! -z $TEMPLATE ]]&& batch+=" --url=$TEMPLATE@$POOL"
batch+=" --telemetry=$API_PORT --log-file=$LOG"
[[ ! -z $ADDITION ]] && batch+=" $ADDITION"

echo -e "${GREEN}> Starting miniZ: $batch${WHITE}"

unbuffer $batch 2>&1 | tee $LOG
